---
title: "&#39; Por último &#39; no puede aparecer fuera de un &#39; Try &#39; instrucción"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords: BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
caps.latest.revision: "7"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: c06b04940ad9aac030cb6ffa018cf56ce8cf3e6e
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 11/21/2017
---
# <a name="39finally39-cannot-appear-outside-a-39try39-statement"></a>&#39; Por último &#39; no puede aparecer fuera de un &#39; Try &#39; instrucción
`Finally` se usa para completar un bloque `Try...Catch...Finally` ; por lo tanto, solo puede aparecer una vez al final del bloque. O bien hay un elemento `Finally`innecesario, o la instrucción `Finally` aparece fuera de los límites de su bloque `Try` correspondiente.  
  
 **Id. de error:** BC30382  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1.  Busque y quite el innecesarios `Finally` instrucción.  
  
2.  Mueva la instrucción `Finally` a la ubicación adecuada del código.  
  
## <a name="see-also"></a>Vea también  
 [Try...Catch...Finally (instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Información general de Visual Basic del control estructurado de excepciones](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)
