---
title: "&#39; Por último &#39; no puede aparecer fuera de un &#39; Try &#39; instrucción"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords: BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
caps.latest.revision: "7"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 259df1345b443d5023ebecd457c81167d0799fe0
ms.sourcegitcommit: 34ec7753acf76f90a0fa845235ef06663dc9e36e
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 12/21/2017
---
# <a name="39finally39-cannot-appear-outside-a-39try39-statement"></a>&#39; Por último &#39; no puede aparecer fuera de un &#39; Try &#39; instrucción
`Finally` se usa para completar un bloque `Try...Catch...Finally` ; por lo tanto, solo puede aparecer una vez al final del bloque. O bien hay un elemento `Finally`innecesario, o la instrucción `Finally` aparece fuera de los límites de su bloque `Try` correspondiente.  
  
 **Id. de error:** BC30382  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1.  Busque y quite el innecesarios `Finally` instrucción.  
  
2.  Mueva la instrucción `Finally` a la ubicación adecuada del código.  
  
## <a name="see-also"></a>Vea también  
 [Try...Catch...Finally (instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
