---
title: "&#39; de Error &#39; las instrucciones no son válidos dentro de &#39; Usar &#39; instrucciones"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc36013
- bc36013
helpviewer_keywords: BC36013
ms.assetid: 5b399bf9-6595-46e0-a808-378f6c28568b
caps.latest.revision: "10"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 4aa95d2c19a050f9cc57e349a773c13481a554d4
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 01/19/2018
---
# <a name="39on-error39-statements-are-not-valid-within-39using39-statements"></a>&#39; de Error &#39; las instrucciones no son válidos dentro de &#39; Usar &#39; instrucciones
Una instrucción `On Error` aparece dentro de una instrucción `Using` , pero no es válida en ese contexto.  
  
 **Identificador de error:** BC36013  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
-   Use el control de errores estructurado, como un bloque `Try…Catch` , en lugar de la instrucción `On Error` .  
  
## <a name="see-also"></a>Vea también  
   
 [Elegir cuándo se debe utilizar (Visual Basic) de control de excepciones estructurado y no estructurado](http://msdn.microsoft.com/library/e897d7ca-07e8-45dd-8a6d-a5b2a2fc9b9a)  
 [On Error (instrucción)](../../visual-basic/language-reference/statements/on-error-statement.md)  
 [Cómo: probar el código con un bloque Try... El bloque catch en Visual Basic](http://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally (instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
