---
title: '&#39;Detectar&#39; nunca se alcanzó; el bloque &lt;excepción&gt; se gestionó anteriormente en el mismo &#39;intente&#39; instrucción'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: f84eced8f36e404886ae1b435bbb3ba1beffebbd
ms.sourcegitcommit: efff8f331fd9467f093f8ab8d23a203d6ecb5b60
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 09/03/2018
ms.locfileid: "43481323"
---
# <a name="39catch39-block-never-reached-ltexceptiongt-handled-above-in-the-same-39try39-statement"></a>&#39;Detectar&#39; nunca se alcanzó; el bloque &lt;excepción&gt; se gestionó anteriormente en el mismo &#39;intente&#39; instrucción
Un bloque `Catch` del código no se puede alcanzar porque se controla en un bloque `Try` precedente.  
  
 De forma predeterminada, este mensaje es una advertencia. Para obtener más información sobre cómo ocultar las advertencias o cómo tratarlas como errores, vea [configurar advertencias en Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)  
  
 **Identificador de error:** BC42031  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
-   Quite la instrucción redundante.  
  
## <a name="see-also"></a>Vea también  
 [Cómo: detectar una excepción en Visual Basic](https://msdn.microsoft.com/library/f3063c89-d2bf-49b1-91b5-b87edfb18b95)  
 [Cómo: probar el código con un bloque Try... El bloque catch en Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Cómo: filtrar errores en un bloque Catch en Visual Basic](https://msdn.microsoft.com/library/85964d0a-56e7-4301-a96e-5eaea23b7b9b)  
 [Tutorial: Control estructurado de excepciones (Visual Basic)](https://msdn.microsoft.com/library/440da655-4b32-490b-8b16-bfe46f41fa76)  
 [Try...Catch...Finally (instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
