---
title: Bloque 'Catch' nunca se alcanzó. <exception> se gestionó anteriormente en la misma instrucción 'Try'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 0fcb4db60ecc8236293e74409727b20b5fccdceb
ms.sourcegitcommit: 14355b4b2fe5bcf874cac96d0a9e6376b567e4c7
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 01/30/2019
ms.locfileid: "55265381"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Bloque 'Catch' nunca se alcanzó. \<excepción > se gestionó anteriormente en la misma instrucción 'Try'
Un bloque `Catch` del código no se puede alcanzar porque se controla en un bloque `Try` precedente.  
  
 De forma predeterminada, este mensaje es una advertencia. Para más información sobre cómo ocultar las advertencias o cómo tratarlas como errores, vea [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Identificador de error:** BC42031  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
-   Quite la instrucción redundante.  
  
## <a name="see-also"></a>Vea también
- [Cómo: Detectar una excepción en Visual Basic](https://msdn.microsoft.com/library/f3063c89-d2bf-49b1-91b5-b87edfb18b95)
- [Cómo: Probar el código con un bloque Try... El bloque catch en Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)
- [Cómo: Filtrar errores en un bloque Catch en Visual Basic](https://msdn.microsoft.com/library/85964d0a-56e7-4301-a96e-5eaea23b7b9b)
- [Tutorial: (Visual Basic) de control de excepciones estructurado](https://msdn.microsoft.com/library/440da655-4b32-490b-8b16-bfe46f41fa76)
- [Try...Catch...Finally (instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
